core/facade.py
core/views.py

Fixed problem with migrate

---

core/views.py
templates/chart.html

SetUp basic token

---

core/facade.py
core/views.py
templates/group_by_week.html

Adiciona média do período

---

core/urls.py
core/views.py

- Permite requisitar dados de um período caso tenha um Token válido.
this close #27

Limita acesso a dados personalizados

---

core/static/style.css
core/urls.py
core/views.py
templates/about.html
templates/base.html
templates/index.html
templates/main-nav.html
templates/ops.html

- Alguns testes com materialize

Melhorias no frontend

---

golme/settings.py
requirements.txt

SetUp Cloudinary for static files

---

templates/group_by_week.html

Refatora group_by_week.html template

---

templates/base.html
templates/with_chart.html

SetUp TagManager for Analytics

---

README.md
core/static/style.css
core/urls.py
core/views.py
templates/about.html
templates/docs.html
templates/main-nav.html

Improves documentation

---

core/urls.py
core/views.py

- setup summary endpoint
This close #54

SetUp Summary

---

requirements.txt
templates/about.html
templates/docs.html
templates/main-nav.html

- atualiza dependencias
- melhora informações para contato
Esta relacionado a Issue #10

Improve contact details

---

core/management/commands/update_lme.py

`python manage.py update_lme -sd '01-03-2012'` no formato mm-dd-YYYY

Define um parâmetro para a data inicial no intervalo de datas do script

---

core/admin.py
core/new_data.py

BugFix - Fix Dezembro Key

---

core/forms.py
core/views.py
templates/profile_update.html

Fixes error that erased token when updating profile without photo
This close #85

HotFix - Token deleted after update profile

---

core/views.py

HotFix - Permite incorporar cotacoes

---

core/management/commands/update_lme2.py
requirements.txt

— Corrige atualização desnecessária quando existe obj
— Atualiza dependência
This close #92 and close #91

HotFix update lme.

---

core/views.py

Refatora sumario

---

core/facade.py

API result order

---

core/facade.py

HotFix API result order

---

core/facade.py

- State Funeral of Queen Elizabeth II
Está relacionado a issue #105

Remove ferido útil

---

core/urls.py

Permite pegar os dados para gerar o gráfico passando data inicial e final como parametros.
This close #108

JSON do Gráfico por período

---

core/facade.py

HotFix Erro em data final das variações
